using System.IO.Compression;
using Hoaii.Infrastructure;
using Hoaii.Web.Services;
using Hoaii.Web.Services.Admin;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllersWithViews();

// The build-time static-asset compression (the .br/.gz files MapStaticAssets' manifest points
// to) doesn't get generated by `dotnet publish` on this machine — see
// tools/strip-compressed-assets.js. Stripping those broken manifest entries before every deploy
// avoids the blank-page bug, but it also means every response (HTML, CSS, JS) was going out
// completely uncompressed. Compressing here instead, at runtime, fixes that at the root and
// doesn't depend on the flaky build-time step at all.
builder.Services.AddResponseCompression(options =>
{
    options.EnableForHttps = true;
    options.Providers.Add<BrotliCompressionProvider>();
    options.Providers.Add<GzipCompressionProvider>();
});
builder.Services.Configure<BrotliCompressionProviderOptions>(options => options.Level = CompressionLevel.Fastest);
builder.Services.Configure<GzipCompressionProviderOptions>(options => options.Level = CompressionLevel.Fastest);

// Razor's default encoder escapes every non-ASCII character, so Vietnamese text coming from the
// DB rendered as "&#x1EF0;A CH&#x1ECC;N…" — correct in a browser but bloated and unreadable in
// source. Allow the full Unicode range so it is emitted as-is.
builder.Services.Configure<Microsoft.Extensions.WebEncoders.WebEncoderOptions>(options =>
    options.TextEncoderSettings = new System.Text.Encodings.Web.TextEncoderSettings(
        System.Text.Unicode.UnicodeRanges.All));

builder.Services.AddDbContext<HoaiiDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddHttpContextAccessor();
builder.Services.AddDistributedMemoryCache();
builder.Services.AddMemoryCache();
builder.Services.AddSession(options =>
{
    options.IdleTimeout = TimeSpan.FromDays(7);
    options.Cookie.IsEssential = true;
});
builder.Services.AddScoped<CartService>();
builder.Services.AddScoped<OtpService>();
builder.Services.AddScoped<AdminAuthService>();
builder.Services.AddScoped<MediaService>();
builder.Services.AddScoped<OrderWorkflowService>();
builder.Services.AddScoped<SiteSettingsService>();
builder.Services.AddScoped<NavigationService>();
builder.Services.AddScoped<PageContentService>();
builder.Services.AddScoped<EmailSender>();

builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        options.LoginPath = "/tai-khoan/dang-nhap";
        options.AccessDeniedPath = "/tai-khoan/dang-nhap";
        options.ExpireTimeSpan = TimeSpan.FromDays(30);
        options.SlidingExpiration = true;
        options.Cookie.Name = "hoaii.auth";
    })
    // A separate cookie for the admin area — its own name, its own login path, a shorter life.
    // Signing out as a customer never logs the admin out and vice-versa.
    .AddCookie(AdminAuth.Scheme, options =>
    {
        options.LoginPath = "/admin/dang-nhap";
        options.AccessDeniedPath = "/admin/khong-co-quyen";
        options.LogoutPath = "/admin/dang-xuat";
        options.ExpireTimeSpan = TimeSpan.FromHours(8);
        options.SlidingExpiration = true;
        options.Cookie.Name = "hoaii.admin";
    });

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy(AdminAuth.PolicyAdmin, policy => policy
        .AddAuthenticationSchemes(AdminAuth.Scheme)
        .RequireAuthenticatedUser());

    options.AddPolicy(AdminAuth.PolicyOwner, policy => policy
        .AddAuthenticationSchemes(AdminAuth.Scheme)
        .RequireAuthenticatedUser()
        .RequireClaim(AdminAuth.RoleClaim, nameof(Hoaii.Domain.Entities.AdminRole.Owner)));
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

// Must run before anything that writes to the response body — static files, uploads, and MVC
// views alike — so it can wrap all of them, not just one.
app.UseResponseCompression();

// MapStaticAssets() below only serves the fixed set of files known at build/publish time (it's
// backed by the fingerprint manifest, same one tools/strip-compressed-assets.js patches) — it
// never sees files MediaService writes to wwwroot/uploads at runtime. Without this, every
// admin-uploaded image (media library, product photos, blog images) 404s and shows as a broken/
// blank image on the storefront and in the picker, even though the upload itself "succeeded".
Directory.CreateDirectory(Path.Combine(app.Environment.WebRootPath, "uploads"));
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new PhysicalFileProvider(Path.Combine(app.Environment.WebRootPath, "uploads")),
    RequestPath = "/uploads",
});

app.UseStatusCodePagesWithReExecute("/loi/{0}");
app.UseRouting();

app.UseSession();
app.UseAuthentication();
app.UseAuthorization();

app.MapStaticAssets();

app.MapControllerRoute(
    name: "status-code-page",
    pattern: "loi/{code:int}",
    defaults: new { controller = "Home", action = "StatusCodePage" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "category",
    pattern: "danh-muc/{slug}",
    defaults: new { controller = "Category", action = "Index" })
    .WithStaticAssets();

// The "Quà theo dịp" landing pages. These sit at the top level rather than under danh-muc/
// because they are not category grids — OccasionController owns the list of valid routes.
app.MapControllerRoute(
    name: "occasion-landing",
    pattern: "qua-theo-dip",
    defaults: new { controller = "Occasion", action = "Index", route = "qua-theo-dip" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "occasion-personal",
    pattern: "qua-tang-ca-nhan",
    defaults: new { controller = "Occasion", action = "Index", route = "qua-tang-ca-nhan" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "product",
    pattern: "san-pham/{slug}",
    defaults: new { controller = "Product", action = "Details" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "cart-add",
    pattern: "gio-hang/them",
    defaults: new { controller = "Cart", action = "Add" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "cart-update",
    pattern: "gio-hang/cap-nhat",
    defaults: new { controller = "Cart", action = "UpdateQty" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "cart-remove",
    pattern: "gio-hang/xoa",
    defaults: new { controller = "Cart", action = "Remove" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "cart-apply-voucher",
    pattern: "gio-hang/ap-dung-ma",
    defaults: new { controller = "Cart", action = "ApplyVoucher" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "cart-remove-voucher",
    pattern: "gio-hang/xoa-ma",
    defaults: new { controller = "Cart", action = "RemoveVoucher" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "cart",
    pattern: "gio-hang",
    defaults: new { controller = "Cart", action = "Index" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "search",
    pattern: "tim-kiem",
    defaults: new { controller = "Search", action = "Index" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "blog-details",
    pattern: "blog/{slug}",
    defaults: new { controller = "Blog", action = "Details" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "blog",
    pattern: "blog",
    defaults: new { controller = "Blog", action = "Index" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "about-us",
    pattern: "ve-chung-toi",
    defaults: new { controller = "Page", action = "AboutUs" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "partners",
    pattern: "hop-tac",
    defaults: new { controller = "Page", action = "Partners" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "contact",
    pattern: "lien-he",
    defaults: new { controller = "Page", action = "Contact" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "owner-info",
    pattern: "chinh-sach/thong-tin-chu-so-huu",
    defaults: new { controller = "Page", action = "OwnerInfo" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "policy",
    pattern: "chinh-sach/{slug}",
    defaults: new { controller = "Page", action = "Policy" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "checkout-place-order",
    pattern: "thanh-toan/dat-hang",
    defaults: new { controller = "Checkout", action = "PlaceOrder" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "checkout-confirmation",
    pattern: "thanh-toan/xac-nhan/{orderNumber}",
    defaults: new { controller = "Checkout", action = "Confirmation" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "checkout",
    pattern: "thanh-toan",
    defaults: new { controller = "Checkout", action = "Index" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "account-login",
    pattern: "tai-khoan/dang-nhap",
    defaults: new { controller = "Account", action = "Login" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "account-verify-otp",
    pattern: "tai-khoan/xac-thuc",
    defaults: new { controller = "Account", action = "VerifyOtp" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "account-resend-otp",
    pattern: "tai-khoan/gui-lai-ma",
    defaults: new { controller = "Account", action = "ResendOtp" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "account-logout",
    pattern: "tai-khoan/dang-xuat",
    defaults: new { controller = "Account", action = "Logout" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "account-orders",
    pattern: "tai-khoan/don-hang",
    defaults: new { controller = "Account", action = "Orders" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "account-addresses",
    pattern: "tai-khoan/dia-chi",
    defaults: new { controller = "Account", action = "Addresses" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "account",
    pattern: "tai-khoan",
    defaults: new { controller = "Account", action = "Profile" })
    .WithStaticAssets();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}")
    .WithStaticAssets();

// The admin area uses attribute routing (every route is spelled out on the controller), so it
// needs the attribute-route endpoint map in addition to the conventional routes above.
app.MapControllers();

// Create the first Owner account if none exists, so /admin is reachable on a fresh database.
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<HoaiiDbContext>();
    await AdminAuthService.EnsureSeedAdminAsync(db, app.Configuration);
    await PolicyPageSeeder.EnsureSeedAsync(db);
    await HomeContentSeeder.EnsureSeedAsync(db);
    await NavigationSeeder.EnsureSeedAsync(db);
    await VoucherSeeder.EnsureSeedAsync(db);
    await PartnerLogoSeeder.EnsureSeedAsync(db);
    await CategoryGroupSeeder.EnsureSeedAsync(db);
    await MegaMenuColumnMigrationSeeder.EnsureSeedAsync(db);
}

app.Run();
