// <auto-generated />
using Hoaii.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hoaii.Infrastructure.Migrations
{
    [DbContext(typeof(HoaiiDbContext))]
    [Migration("20260709050541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hoaii.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Trà",
                            Slug = "tra",
                            SortOrder = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Khăn",
                            Slug = "khan",
                            SortOrder = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tượng gốm",
                            Slug = "tuong-gom",
                            SortOrder = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rượu",
                            Slug = "ruou",
                            SortOrder = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Quà tết",
                            Slug = "qua-tet",
                            SortOrder = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Quà trung thu",
                            Slug = "qua-trung-thu",
                            SortOrder = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Quà giáng sinh",
                            Slug = "qua-giang-sinh",
                            SortOrder = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Quà tặng bố mẹ",
                            Slug = "qua-tang-bo-me",
                            SortOrder = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Quà tặng người ấy",
                            Slug = "qua-tang-nguoi-ay",
                            SortOrder = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ngày quốc tế phụ nữ",
                            Slug = "ngay-quoc-te-phu-nu",
                            SortOrder = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ngày lễ tình yêu",
                            Slug = "ngay-le-tinh-yeu",
                            SortOrder = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Quà tặng theo dịp",
                            Slug = "qua-tang-theo-dip",
                            SortOrder = 12,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Badge")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceModifier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.Product", b =>
                {
                    b.HasOne("Hoaii.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Hoaii.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("Hoaii.Domain.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
