// <auto-generated />
using Hoaii.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hoaii.Infrastructure.Migrations
{
    [DbContext(typeof(HoaiiDbContext))]
    [Migration("20260709054229_SeedMoreProductsAndVariants")]
    partial class SeedMoreProductsAndVariants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hoaii.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Trà",
                            Slug = "tra",
                            SortOrder = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Khăn",
                            Slug = "khan",
                            SortOrder = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tượng gốm",
                            Slug = "tuong-gom",
                            SortOrder = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rượu",
                            Slug = "ruou",
                            SortOrder = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Quà tết",
                            Slug = "qua-tet",
                            SortOrder = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Quà trung thu",
                            Slug = "qua-trung-thu",
                            SortOrder = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Quà giáng sinh",
                            Slug = "qua-giang-sinh",
                            SortOrder = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Quà tặng bố mẹ",
                            Slug = "qua-tang-bo-me",
                            SortOrder = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Quà tặng người ấy",
                            Slug = "qua-tang-nguoi-ay",
                            SortOrder = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ngày quốc tế phụ nữ",
                            Slug = "ngay-quoc-te-phu-nu",
                            SortOrder = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ngày lễ tình yêu",
                            Slug = "ngay-le-tinh-yeu",
                            SortOrder = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Quà tặng theo dịp",
                            Slug = "qua-tang-theo-dip",
                            SortOrder = 12,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Badge")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = 1,
                            CategoryId = 1,
                            IsFeatured = false,
                            Name = "Trà sen vàng",
                            Price = 250000m,
                            Slug = "tra-sen-vang"
                        },
                        new
                        {
                            Id = 2,
                            Badge = 2,
                            CategoryId = 1,
                            CompareAtPrice = 380000m,
                            IsFeatured = false,
                            Name = "Trà ô long thượng hạng",
                            Price = 320000m,
                            Slug = "tra-o-long-thuong-hang"
                        },
                        new
                        {
                            Id = 3,
                            Badge = 0,
                            CategoryId = 1,
                            IsFeatured = false,
                            Name = "Trà sen Tây Hồ hộp gỗ",
                            Price = 410000m,
                            Slug = "tra-sen-tay-ho-hop-go"
                        },
                        new
                        {
                            Id = 4,
                            Badge = 1,
                            CategoryId = 1,
                            IsFeatured = false,
                            Name = "Trà shan tuyết cổ thụ",
                            Price = 550000m,
                            Slug = "tra-shan-tuyet-co-thu"
                        },
                        new
                        {
                            Id = 5,
                            Badge = 3,
                            CategoryId = 1,
                            IsFeatured = false,
                            Name = "Trà lài ướp hương",
                            Price = 190000m,
                            Slug = "tra-lai-uop-huong"
                        },
                        new
                        {
                            Id = 6,
                            Badge = 0,
                            CategoryId = 1,
                            IsFeatured = false,
                            Name = "Trà đen kỵ sữa",
                            Price = 220000m,
                            Slug = "tra-den-ky-sua"
                        },
                        new
                        {
                            Id = 7,
                            Badge = 2,
                            CategoryId = 1,
                            CompareAtPrice = 210000m,
                            IsFeatured = false,
                            Name = "Trà thảo mộc detox",
                            Price = 175000m,
                            Slug = "tra-thao-moc-detox"
                        },
                        new
                        {
                            Id = 8,
                            Badge = 0,
                            CategoryId = 1,
                            IsFeatured = false,
                            Name = "Trà atiso Đà Lạt",
                            Price = 205000m,
                            Slug = "tra-atiso-da-lat"
                        },
                        new
                        {
                            Id = 9,
                            Badge = 0,
                            CategoryId = 1,
                            IsFeatured = false,
                            Name = "Trà oolong túi lọc cao cấp",
                            Price = 260000m,
                            Slug = "tra-oolong-tui-loc-cao-cap"
                        },
                        new
                        {
                            Id = 10,
                            Badge = 0,
                            CategoryId = 1,
                            IsFeatured = false,
                            Name = "Trà bạc hà hộp thiếc",
                            Price = 165000m,
                            Slug = "tra-bac-ha-hop-thiec"
                        },
                        new
                        {
                            Id = 20,
                            Badge = 1,
                            CategoryId = 5,
                            IsFeatured = true,
                            Name = "Hộp quà Tết Xuân Phú Quý",
                            Price = 890000m,
                            Slug = "hop-qua-tet-xuan-phu-quy"
                        },
                        new
                        {
                            Id = 21,
                            Badge = 0,
                            CategoryId = 5,
                            IsFeatured = false,
                            Name = "Hộp quà Tết An Khang",
                            Price = 650000m,
                            Slug = "hop-qua-tet-an-khang"
                        });
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceModifier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hộp 4 túi / màu vàng",
                            PriceModifier = 0m,
                            ProductId = 1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hộp 4 túi / màu đỏ",
                            PriceModifier = 0m,
                            ProductId = 1,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hộp 8 túi / màu vàng",
                            PriceModifier = 80000m,
                            ProductId = 1,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hộp gỗ nhỏ",
                            PriceModifier = 0m,
                            ProductId = 3,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hộp gỗ lớn",
                            PriceModifier = 120000m,
                            ProductId = 3,
                            StockQuantity = 10
                        });
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.Product", b =>
                {
                    b.HasOne("Hoaii.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Hoaii.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("Hoaii.Domain.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Hoaii.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
